Repository Jerry-Vrrr/rec-me, pull requests merged in 2022-04, with the labels that each got.

#6 Feature/main dashboard/ml
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/App/App.js
  src/components/App/_App.css
  src/components/App/_App.scss
  src/components/FavCard/FavCard.js
  src/components/Favorites/Favorites.js
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/contexts/FavoriteContext.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/style.css
  src/style.scss
Labels: feature / enhancement

#8 Feature/global state/ka
  src/apiCalls.js
  src/components/App/App.js
  src/components/BubbleBox/BubbleBox.js
  src/contexts/DataContext.js
Labels: feature / enhancement

#11 Feature/dashboard small bubbles/em
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/App/_App.scss
  src/components/BigBubble/BigBubble.js
  src/components/BigBubble/_BigBubble.scss
  src/components/BubbleBox/BubbleBox.js
  src/components/BubbleBox/_BubbleBox.scss
  src/components/SmallBubble/SmallBubble.js
  src/components/SmallBubble/_SmallBubble.scss
  src/contexts/DataContext.js
Labels: feature / enhancement

#19 Feature/single movie page
  src/components/BubbleBox/BubbleBox.js
  src/components/RelatedArtist/RelatedArtist.js
  src/components/RelatedArtist/_RelatedArtist.scss
  src/components/RelatedArtists/RelatedArtist.js
  src/components/SingleArtist/SingleArtist.js
  src/components/SingleArtist/_SingleArtist.scss
Labels: feature / enhancement

#22 Feature/testing single movie/ml
  cypress/integration/main-dashboard-spec.js
  cypress/integration/single-artist-spec.js
  src/components/BigBubble/BigBubble.js
  src/components/BigBubble/_BigBubble.scss
  src/components/SingleArtist/SingleArtist.js
Labels: testing

#26 Feature/search bar/ka
  src/components/App/App.js
  src/components/BubbleBox/BubbleBox.js
  src/components/Form/_Form.scss
  src/components/Header/Header.js
  src/components/SearchBar/SearchBar.js
  src/components/SearchBar/_SearchBar.scss
  src/data.js
Labels: feature / enhancement

#35 Feature/hide api key
  .gitignore
  src/apiCalls.js
  src/components/App/App.js
Labels: feature / enhancement

#33 Feature/default artist images/ml
  src/components/BigBubble/BigBubble.js
  src/components/SmallBubble/SmallBubble.js
Labels: bug / refactor

#38 Feature/error handling/ml
  src/components/App/App.js
  src/components/BigBubble/BigBubble.js
  src/components/BubbleBox/BubbleBox.js
  src/components/Error/Error.js
  src/components/Header/Header.js
  src/components/RelatedArtist/RelatedArtist.js
  src/components/SingleArtist/SingleArtist.js
  src/components/SmallBubble/SmallBubble.js
  src/contexts/DataContext.js
Labels: bug / refactor, feature / enhancement

#43 Feature/loading/ml
  src/components/BubbleBox/BubbleBox.js
  src/components/BubbleBox/_BubbleBox.scss
  src/components/GameBox/GameBox.js
  src/contexts/DataContext.js
Labels: bug / refactor

#47 Testing/search bar/ml
  cypress/integration/game-spec.js
  cypress/integration/main-dashboard-spec.js
  cypress/integration/search-bar-spec.js
  cypress/integration/single-artist-spec.js
  src/apiCalls.js
  src/components/App/App.js
  src/components/BigBubble/BigBubble.js
  src/components/BubbleBox/BubbleBox.js
  src/components/Header/Header.js
  src/components/SearchBar/_SearchBar.scss
  src/components/SmallBubble/SmallBubble.js
  src/contexts/DataContext.js
  src/contexts/GameContext.js
Labels: bug / refactor, testing

#49 Feature/gamify/jv
  src/components/App/App.js
  src/components/BubbleBox/BubbleBox.js
  src/components/BubbleBox/Light-Up-Beach-Ball-4.webp
  src/components/BubbleBox/_BubbleBox.scss
  src/components/Error/Error.js
  src/components/Error/_Error.scss
  src/components/GameBox/GameBox.js
  src/components/GameBox/_GameBox.scss
  src/components/Header/Header.js
  src/components/Header/_Header.scss
  src/components/Loader/Loader.js
  src/data.js
  src/images/beach-balls.png
  src/images/vinyl.svg
Labels: bug / refactor, feature / enhancement, styling
